---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-build-push-run
  namespace: tekton-builds
spec:
  pipelineRef:
    name: clone-build-push
  serviceAccountName: pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"
  # Parameters for the Pipeline
  params:
  - name: GIT_URL
    value: https://github.com/emilpeychev/kind-cluster-cilium.git
  - name: GIT_BRANCH
    value: master
  - name: COMMIT_SHA
    value: ""  # Optional: specify a commit SHA to checkout, leave empty for latest
  - name: IMAGE_REPO
    value: harbor.local/library/demo-app
  - name: IMAGE_TAG
    value: "0.1"
