apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cosign-sign
  namespace: tekton-builds
spec:
  params:
    - name: IMAGE_URL
      type: string

  steps:
    - name: generate-sbom
      image: aquasec/trivy:latest
      script: |
        #!/bin/sh
        set -e
        
        echo "Generating SBOM for image: $(params.IMAGE_URL)"
        
        trivy image \
          --format cyclonedx \
          --output /workspace/sbom.json \
          --insecure \
          $(params.IMAGE_URL)
        
        echo "SBOM generated successfully"
        ls -lh /workspace/sbom.json
      volumeMounts:
        - name: sbom-storage
          mountPath: /workspace
    - name: sign
      image: gcr.io/projectsigstore/cosign:v2.2.0
      env:
        - name: COSIGN_PASSWORD
          value: ""
        - name: DOCKER_CONFIG
          value: /docker-config
      command:
        - cosign
      args:
        - sign
        - --key
        - /cosign/cosign.key
        - --allow-insecure-registry
        - --yes
        - $(params.IMAGE_URL)
      volumeMounts:
        - name: cosign-key
          mountPath: /cosign
        - name: docker-config
          mountPath: /docker-config
    - name: attest-sbom
      image: gcr.io/projectsigstore/cosign:v2.2.0
      env:
        - name: COSIGN_PASSWORD
          value: ""
        - name: DOCKER_CONFIG
          value: /docker-config
      command:
        - cosign
      args:
        - attest
        - --key
        - /cosign/cosign.key
        - --predicate
        - /workspace/sbom.json
        - --type
        - cyclonedx
        - --allow-insecure-registry
        - --yes
        - $(params.IMAGE_URL)
      volumeMounts:
        - name: cosign-key
          mountPath: /cosign
        - name: docker-config
          mountPath: /docker-config
        - name: sbom-storage
          mountPath: /workspace
        - name: docker-config
          mountPath: /docker-config
  volumes:
    - name: cosign-key
      secret:
        secretName: cosign-key
    - name: docker-config
      secret:
        secretName: harbor-registry
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: sbom-storage
      emptyDir: {}
