apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cosign-sign
  namespace: tekton-builds
spec:
  params:
    - name: IMAGE_URL
      type: string

  steps:
    - name: sign
      image: gcr.io/projectsigstore/cosign:v2.2.0
      env:
        - name: COSIGN_PASSWORD
          value: ""
        - name: DOCKER_CONFIG
          value: /docker-config
      command:
        - cosign
      args:
        - sign
        - --key
        - /cosign/cosign.key
        - --allow-insecure-registry
        - --yes
        - $(params.IMAGE_URL)
      volumeMounts:
        - name: cosign-key
          mountPath: /cosign
        - name: docker-config
          mountPath: /docker-config

  volumes:
    - name: cosign-key
      secret:
        secretName: cosign-key
    - name: docker-config
      secret:
        secretName: harbor-registry
        items:
          - key: .dockerconfigjson
            path: config.json
