apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repo
  namespace: tekton-builds
spec:
  workspaces:
    - name: output
    - name: ssh-directory
      optional: true
  params:
    - name: GIT_BRANCH
      type: string
      default: master
    - name: GIT_URL
      type: string
  results:
    - name: timestamp
      description: Build timestamp for image tag (YYYYMMDD-HHMMSS)
  steps:
    - name: git-clone
      image: alpine/git
      env:
        - name: HOME
          value: /home/git
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/bin/sh
        mkdir -p ~/.ssh
        cp $(workspaces.ssh-directory.path)/* ~/.ssh/ 2>/dev/null || true
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/* 2>/dev/null || true
        ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null
        git clone --branch $(params.GIT_BRANCH) $(params.GIT_URL) $(workspaces.output.path)
        date -u +"%Y%m%d-%H%M%S" | tr -d '\n' > $(results.timestamp.path)
