apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repo
  namespace: tekton-builds
spec:
  workspaces:
    - name: output
  params:
    - name: GIT_BRANCH
      type: string
      default: master
    - name: GIT_URL
      type: string
  results:
    - name: timestamp
      description: Build timestamp for image tag (YYYYMMDD-HHMMSS)
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        git clone --branch $(params.GIT_BRANCH) $(params.GIT_URL) $(workspaces.output.path)
        ls -la $(workspaces.output.path)/
        # Generate timestamp for image tag (YYYYMMDD-HHMMSS)
        date -u +"%Y%m%d-%H%M%S" | tr -d '\n' > $(results.timestamp.path)
