apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-push
  namespace: tekton-builds
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE
      type: string
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:v1.12.0
      env:
        - name: HOME
          value: /kaniko
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
      args:
        - --context=$(workspaces.source.path)/demo-app
        - --dockerfile=$(workspaces.source.path)/demo-app/Dockerfile
        - --destination=$(params.IMAGE)
        - --insecure
        - --skip-tls-verify
  volumes:
    - name: docker-config
      secret:
        secretName: harbor-registry
        items:
          - key: .dockerconfigjson
            path: config.json
