apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push-image
  namespace: tekton-builds
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE_URL
      type: string
    - name: IMAGE_URL_LATEST
      type: string
      default: ""
    - name: DOCKERFILE_PATH
      type: string
      default: demo-app/Dockerfile
    - name: CONTEXT_PATH
      type: string
      default: demo-app
  steps:
    - name: kaniko-build
      image: gcr.io/kaniko-project/executor:v1.12.0
      securityContext:
        runAsUser: 0
      env:
        - name: HOME
          value: /kaniko
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
      computeResources:
        limits:
          cpu: "500m"
          memory: "2Gi"
      args:
        - "--context=$(workspaces.source.path)/$(params.CONTEXT_PATH)"
        - "--dockerfile=$(workspaces.source.path)/$(params.DOCKERFILE_PATH)"
        - "--destination=$(params.IMAGE_URL)"
        - "--destination=$(params.IMAGE_URL_LATEST)"
        - "--insecure"
        - "--skip-tls-verify"
        - "--cache=false"
  volumes:
    - name: docker-config
      secret:
        secretName: harbor-registry
        items:
          - key: .dockerconfigjson
            path: config.json
