apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-app
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE_URL
      type: string
      description: The image URL to deploy
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/bin/sh
        set -e
        echo "Deploying image: $(params.IMAGE_URL)"
        # Update the deployment with the new image
        # Uncomment and modify the following line for your deployment:
        # kubectl set image deployment/demo-app demo-app=$(params.IMAGE_URL) -n default
        echo "Deployment complete"
