apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-
  namespace: tekton-builds
spec:
  pipelineRef:
    name: clone-build-push
  serviceAccountName: tekton-build-sa
  podTemplate:
    securityContext:
      fsGroup: 0
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"
  - name: ssh-creds
    secret:
      secretName: github-deploy-key
  params:
  - name: GIT_URL
    value: git@github.com:emilpeychev/kind-cluster-cilium.git
  - name: GIT_BRANCH
    value: master
  - name: IMAGE_REPO
    value: harbor.local/library/demo-app
  - name: VERSION
    value: "v0.1"
