apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: clone-build-push
  namespace: tekton-builds
spec:
  workspaces: 
    - name: shared-data
  params:
    - name: GIT_URL
      type: string
    - name: GIT_BRANCH
      type: string
      default: master
    - name: IMAGE_REPO
      type: string
    - name: VERSION
      type: string
      default: "v0.1"
  tasks: 
    - name: clone-repo
      taskRef:
        name: clone-repo
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: GIT_URL
          value: $(params.GIT_URL)
        - name: GIT_BRANCH
          value: $(params.GIT_BRANCH)
    - name: build-push
      runAfter:
        - clone-repo
      taskRef:
        name: build-push
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE
          value: $(params.IMAGE_REPO):$(params.VERSION)
