apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
  namespace: tekton-builds
spec:
  workspaces: 
    - name: shared-data
  params:
    - name: GIT_URL
      type: string
    - name: GIT_BRANCH
      type: string
      default: main
    - name: IMAGE_URL
      type: string
      description: "Base image repository (without tag), e.g. harbor.local/library/demo-app"
    - name: IMAGE_TAG
      type: string
      default: "version0.1"
      description: "Semantic version tag for the image"

  tasks: 
    - name: clone-repo
      taskRef:
        name: clone-repo
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: GIT_URL
          value: $(params.GIT_URL)
        - name: GIT_BRANCH
          value: $(params.GIT_BRANCH)
    - name: build-and-push-image
      runAfter:
        - clone-repo
      taskRef:
        name: build-and-push-image
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: IMAGE_URL
          value: $(params.IMAGE_REPO):$(tasks.clone-repo.results.commit)
