apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repo
  namespace: tekton-builds
spec:
  workspaces:
    - name: output
    - name: ssh-directory
      optional: true
  params:
    - name: GIT_BRANCH
      type: string
      default: master
    - name: GIT_URL
      type: string
  results:
    - name: timestamp
      description: Build timestamp for image tag (YYYYMMDD-HHMMSS)
  steps:
    - name: git-clone
      image: alpine/git
      env:
        - name: HOME
          value: /root
        - name: GIT_SSH_COMMAND
          value: "ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no"
      securityContext:
        runAsUser: 0
      script: |
        #!/bin/sh
        set -e
        mkdir -p ~/.ssh
        # Copy and rename SSH key
        cp $(workspaces.ssh-directory.path)/ssh-privatekey ~/.ssh/id_rsa 2>/dev/null || true
        cp $(workspaces.ssh-directory.path)/known_hosts ~/.ssh/known_hosts 2>/dev/null || true
        chmod 700 ~/.ssh && chmod 600 ~/.ssh/* 2>/dev/null || true
        
        ls -la ~/.ssh/
        # Convert HTTPS URL to SSH URL
        GIT_URL="$(params.GIT_URL)"
        if echo "$GIT_URL" | grep -q "https://github.com"; then
          GIT_URL=$(echo "$GIT_URL" | sed 's|https://github.com/|git@github.com:|')
        fi
        
        echo "Cloning: $GIT_URL"
        git clone --branch $(params.GIT_BRANCH) "$GIT_URL" $(workspaces.output.path)
        
        echo "=== Clone complete ==="
        ls -la $(workspaces.output.path)
        
        date -u +"%Y%m%d-%H%M%S" | tr -d '\n' > $(results.timestamp.path)
