apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push-image
  namespace: tekton-builds
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE_URL
      type: string
    - name: DOCKERFILE_PATH
      type: string
      default: Dockerfile
    - name: CONTEXT_PATH
      type: string
      default: demo-app
  steps:
    - name: setup-creds
      image: busybox
      script: |
        cp /docker-secret/config.json /kaniko/.docker/config.json
        echo "=== Checking workspace ==="
        ls -la $(workspaces.source.path)/
        ls -la $(workspaces.source.path)/$(params.CONTEXT_PATH)/ || echo "Context path not found"
      volumeMounts:
        - name: docker-secret
          mountPath: /docker-secret
        - name: docker-config
          mountPath: /kaniko/.docker
    - name: kaniko-build
      image: gcr.io/kaniko-project/executor:v1.12.0
      securityContext:
        runAsUser: 0
      env:
        - name: HOME
          value: /workspace
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
      args:
        - "--context=$(workspaces.source.path)/$(params.CONTEXT_PATH)"
        - "--dockerfile=Dockerfile"
        - "--destination=$(params.IMAGE_URL)"
        - "--insecure"
        - "--skip-tls-verify"
        - "--cache=false"
      computeResources: 
        limits:
          cpu: "1"
          memory: "2Gi"
  volumes:
    - name: docker-config
      emptyDir: {}
    - name: docker-secret
      secret:
        secretName: harbor-registry
        items:
          - key: .dockerconfigjson
            path: config.json
