apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: clone-repo
  namespace: tekton-builds
spec:
  workspaces:
    - name: output
  params:
    - name: GIT_URL
      type: string
    - name: GIT_BRANCH
      type: string
      default: master
  steps:
    - name: clone
      image: alpine/git
      env:
        - name: HOME
          value: /tekton/home
      volumeMounts:
        - name: tekton-home
          mountPath: /tekton/home
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/bin/sh
        set -eu
        git config --global --add safe.directory '*'
        git clone --depth 1 --branch $(params.GIT_BRANCH) $(params.GIT_URL) $(workspaces.output.path)
  volumes:
    - name: tekton-home
      emptyDir: {}
