apiVersion: v1
kind: Secret
metadata:
  name: harbor-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
# This file is a template and MUST NOT contain real credentials.
# Password is intentionally omitted so secrets are not committed to git.
stringData:
  name: harbor-helm
  url: https://harbor.local
  type: helm
  enableOCI: "true"
  username: "robot$argocd"
  # password: <set at install-time from .harbor-robot-pass.env>
  insecureSkipServerVerification: "true"
