apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Observability stack (Kiali, Prometheus, Grafana)
  # OCI Helm repo - both formats for compatibility
  sourceRepos:
    - harbor.local
    - harbor.local/helm

  destinations:
    - namespace: istio-system
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  roles:
    - name: observability-admin
      description: Full access for observability admins
      policies:
        - p, proj:observability-project:observability-admin, applications, *, observability-project/*, allow
