apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Observability stack (Kiali, Prometheus, Grafana)

  sourceRepos:
    - harbor.local
    - harbor.local/helm

  destinations:
    - namespace: istio-system
      server: https://kubernetes.default.svc
    - namespace: kiali
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  roles:
    - name: observability-admin
      description: Full access for observability admins
      policies:
        - p, proj:observability-project:observability-admin, applications, *, observability-project/*, allow
