apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    labels:
      app.kubernetes.io/part-of: observability
spec:
  description: Observability stack (Kiali, Prometheus, Grafana)

  sourceRepos:
    - harbor.local
    - harbor.local/helm

  destinations:
    - namespace: istio-system
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding

  roles:
    - name: observability-admin
      description: Full access for observability admins
      policies:
        - p, proj:observability-project:observability-admin, applications, *, observability-project/*, allow
