#!/usr/bin/env bash
set -euo pipefail

echo "🧪 MANUAL TESTING COMMANDS"
echo "=========================="
echo ""

echo "1️⃣ BASIC CLUSTER TESTS"
echo "----------------------"
echo "kubectl cluster-info"
echo "kubectl get nodes -o wide"
echo "kubectl get pods --all-namespaces | grep -v Running"
echo ""

echo "2️⃣ NETWORKING TESTS"
echo "-------------------"
echo "# Test Gateway IP"
echo "kubectl get svc -n istio-gateway"
echo ""
echo "# Test internal connectivity"
echo "kubectl run testpod --image=busybox:1.28 --rm -i --tty -- sh"
echo "# Inside pod: nslookup harbor.local"
echo "# Inside pod: wget -O- http://harbor-core.harbor.svc.cluster.local"
echo ""

echo "3️⃣ HARBOR REGISTRY TESTS"
echo "------------------------"
echo "# Web interface"
echo "curl -k https://harbor.local"
echo ""
echo "# API test"
echo "curl -k https://harbor.local/api/v2.0/systeminfo"
echo ""
echo "# Docker login test (after Harbor is ready)"
echo "docker login harbor.local -u admin -p Harbor12345"
echo ""

echo "4️⃣ TEKTON PIPELINE TESTS"
echo "------------------------"
echo "# Check pipeline status"
echo "kubectl get pipelinerun -n tekton-builds"
echo ""
echo "# Watch pipeline logs"
echo "kubectl logs -f -n tekton-builds -l tekton.dev/pipelineRun=clone-build-push-run"
echo ""
echo "# Restart pipeline"
echo "./run-pipeline.sh"
echo ""

echo "5️⃣ ARGOCD TESTS"
echo "---------------"
echo "# Get admin password"
echo "kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d; echo"
echo ""
echo "# Check applications"
echo "kubectl get application -n argocd"
echo "kubectl get applicationset -n argocd"
echo ""
echo "# Web interface"
echo "curl -k https://argocd.local"
echo ""

echo "6️⃣ DEMO APPLICATION TESTS"
echo "-------------------------"
echo "# Check demo app"
echo "kubectl get all -n demo-apps"
echo ""
echo "# Test demo app externally"
echo "curl -k https://demo-app1.local"
echo ""

echo "7️⃣ END-TO-END WORKFLOW TEST"
echo "----------------------------"
echo "# Build and deploy workflow:"
echo "# 1. Push code to repository"
echo "# 2. Trigger Tekton pipeline"
echo "./run-pipeline.sh"
echo "# 3. Check image in Harbor"
echo "curl -k -u admin:Harbor12345 https://harbor.local/api/v2.0/projects/library/repositories/demo-app/artifacts"
echo "# 4. ArgoCD should auto-sync and deploy"
echo "kubectl get pods -n demo-apps -w"
echo ""

echo "8️⃣ TROUBLESHOOTING COMMANDS"
echo "---------------------------"
echo "# Check failing pods"
echo "kubectl get pods --all-namespaces --field-selector=status.phase!=Running"
echo ""
echo "# Check events"
echo "kubectl get events --all-namespaces --sort-by='.lastTimestamp' | tail -20"
echo ""
echo "# Check Istio proxy status"
echo "istioctl proxy-status"
echo ""
echo "# Check Gateway API status"
echo "kubectl describe gateway istio-gateway -n istio-gateway"
echo ""
echo "# Check Cilium status"
echo "cilium status"
echo "cilium connectivity test"
echo ""

echo "9️⃣ PERFORMANCE & SCALE TESTS"
echo "----------------------------"
echo "# Resource usage"
echo "kubectl top nodes"
echo "kubectl top pods --all-namespaces | head -20"
echo ""
echo "# Scale demo app"
echo "kubectl scale deployment demo-app1 --replicas=5 -n demo-apps"
echo ""
echo "# Load test (if hey is installed)"
echo "hey -n 100 -c 10 https://demo-app1.local/"
echo ""

echo "🔟 QUICK STATUS CHECK"
echo "--------------------"
echo "./health-check.sh"
echo ""
echo "Run './test-platform.sh' for automated comprehensive testing"