apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Demo API Project (httpbin)
  sourceRepos:
    - '*'
  destinations:
    - namespace: httpbin
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
