apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-tekton
  namespace: argo-events
spec:
  dependencies:
    - name: github-push
      eventSourceName: github
      eventName: push

  triggers:
    - template:
        name: trigger-tekton
        k8s:
          operation: create
          source:
            resource:
              apiVersion: tekton.dev/v1
              kind: PipelineRun
              metadata:
                generateName: github-push-
                namespace: tekton-builds
              spec:
                pipelineRef:
                  name: clone-build-push
                params:
                  - name: GIT_URL
                    value: https://github.com/emilpeychev/kind-cluster-cilium.git
                  - name: GIT_BRANCH
                    value: master
                  - name: IMAGE_REPO
                    value: harbor.local/library/demo-app
                  - name: VERSION
                    value: placeholder
                workspaces:
                  - name: shared-data
                    volumeClaimTemplate:
                      spec:
                        accessModes:
                          - ReadWriteOnce
                        resources:
                          requests:
                            storage: 1Gi
                taskRunTemplate:
                  serviceAccountName: pipeline
          parameters:
            # Use commit SHA as version tag
            - src:
                dependencyName: github-push
                dataKey: body.after
              dest: spec.params.3.value
