# GitHub Webhook Secret for Argo Events
# This secret is used to validate incoming webhooks from GitHub
# IMPORTANT: Change the token value for production use!
---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
  namespace: argo-events
type: Opaque
stringData:
  # This token must match the secret configured in GitHub webhook settings
  # Generate a secure token: openssl rand -hex 32
  secret: "change-this-webhook-secret-token"
