apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-tekton
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: github-push
      eventSourceName: github
      eventName: push
      # Filter only pushes to master branch, skip bot commits
      filters:
        data:
          - path: body.ref
            type: string
            value:
              - refs/heads/master
        script: |-
          local message = event.body.head_commit and event.body.head_commit.message or ""
          if string.find(message, "%[skip ci%]") or string.find(message, "ci: deploy") then
            return false
          end
          return true

  triggers:
    - template:
        name: trigger-tekton
        k8s:
          operation: create
          source:
            resource:
              apiVersion: tekton.dev/v1
              kind: PipelineRun
              metadata:
                generateName: github-push-
                namespace: tekton-builds
              spec:
                pipelineRef:
                  name: clone-build-push
                params:
                  - name: GIT_URL
                    value: https://github.com/emilpeychev/kind-cluster-cilium.git
                  - name: GIT_REPO
                    value: emilpeychev/kind-cluster-cilium
                  - name: GIT_BRANCH
                    value: master
                  - name: IMAGE_REPO
                    value: harbor.local/library/demo-app
                  - name: VERSION
                    value: placeholder-timestamp
                  - name: COMMIT_SHA
                    value: placeholder-sha
                workspaces:
                  - name: shared-data
                    volumeClaimTemplate:
                      spec:
                        accessModes:
                          - ReadWriteOnce
                        resources:
                          requests:
                            storage: 1Gi
                  - name: ssh-creds
                    secret:
                      secretName: github-deploy-key
                taskRunTemplate:
                  serviceAccountName: tekton-build-sa
          parameters:
            # Use timestamp as image tag
            - src:
                dependencyName: github-push
                dataTemplate: "{{ now | date \"20060102-150405\" }}"
              dest: spec.params[?(@.name=="VERSION")].value
            # Store commit SHA in metadata
            - src:
                dependencyName: github-push
                dataKey: body.after
              dest: spec.params[?(@.name=="COMMIT_SHA")].value
