apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  jetstream:
    version: "2.10.10"
    replicas: 1
    persistence:
      storageClassName: standard
      accessMode: ReadWriteOnce
      volumeSize: 1Gi
    streamConfig: |
      replicas: 1
