apiVersion: v1
kind: Namespace
metadata:
  name: istio
  annotations:
    argocd.argoproj.io/sync-wave: "0"

---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "0"