apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  namespace: istio
spec:
  hostnames:
  - istio-gateway-istio.istio-gateway
  parentRefs:
  - name: istio-gateway
    namespace: istio-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: echo
      port: 80
