apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kyverno-project
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: security
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  description: Kyverno policy engine
  sourceRepos:
    - git@github.com:emilpeychev/kind-cluster-cilium.git
  destinations:
    - namespace: kyverno
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: kyverno.io
      kind: '*'
    - group: policies.kyverno.io
      kind: '*'
    - group: wgpolicyk8s.io
      kind: '*'
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  roles:
    - name: kyverno-admin
      description: Full access for kyverno admins
      policies:
        - p, proj:kyverno-project:kyverno-admin, applications, *, kyverno-project/*, allow
