apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-workflows-ui
  namespace: argo-workflows
spec:
  parentRefs:
    - name: istio-gateway
      namespace: istio-gateway
  hostnames:
    - "workflows.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argo-workflows-server
          port: 2746
