apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-crds
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: infra-crds
            path: infra
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      project: infra
      source:
        repoURL: git@github.com:emilpeychev/kind-cluster-cilium.git
        targetRevision: dev
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
        - ServerSideApply=true