apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-namespaces
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: infra-namespaces
            path: infra/namespaces
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: infra
      source:
        repoURL: git@github.com:emilpeychev/kind-cluster-cilium.git
        targetRevision: dev
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: false