apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: test-dep
      eventSourceName: webhook-test
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: hello-world-
                namespace: argo-events
              spec:
                containers:
                  - name: hello
                    image: busybox
                    command: ["echo"]
                    args: ["Hello World from Argo Events!"]
                restartPolicy: Never
